import type { CategoryBreakdownEntry, DateFormatKey, Transaction } from '@/types';
import { formatCurrency } from '@/utils/currency';
import { formatDate } from '@/utils/date';

export interface ReportHtmlOptions {
  title: string;
  subtitle: string;
  currency: string;
  dateFormat: DateFormatKey;
  totalIncome: number;
  totalExpense: number;
  profitLoss: number;
  transactionCount: number;
  incomeBreakdown: CategoryBreakdownEntry[];
  expenseBreakdown: CategoryBreakdownEntry[];
  transactions: Transaction[];
}

function breakdownRows(entries: CategoryBreakdownEntry[], currency: string) {
  return entries
    .map(
      (e) => `
      <tr>
        <td>${e.category}</td>
        <td class="right">${formatCurrency(e.total, currency)}</td>
        <td class="right">${e.percentage.toFixed(1)}%</td>
      </tr>`,
    )
    .join('');
}

function transactionRows(
  transactions: Transaction[],
  currency: string,
  dateFormat: DateFormatKey,
) {
  return transactions
    .map(
      (t) => `
      <tr>
        <td>${formatDate(t.date, dateFormat)}</td>
        <td>${t.category}</td>
        <td>${t.type === 'income' ? 'Income' : 'Expense'}</td>
        <td class="right ${t.type}">${t.type === 'income' ? '+' : '-'}${formatCurrency(t.amount, currency)}</td>
      </tr>`,
    )
    .join('');
}

export function buildReportHtml(options: ReportHtmlOptions): string {
  const {
    title,
    subtitle,
    currency,
    dateFormat,
    totalIncome,
    totalExpense,
    profitLoss,
    transactionCount,
    incomeBreakdown,
    expenseBreakdown,
    transactions,
  } = options;

  return `
  <html>
    <head>
      <meta charset="utf-8" />
      <style>
        body { font-family: -apple-system, Roboto, Helvetica, Arial, sans-serif; color: #0B1E3D; padding: 24px; }
        h1 { font-size: 22px; margin-bottom: 2px; color: #0B1E3D; }
        .subtitle { color: #6B7684; margin-bottom: 20px; font-size: 13px; }
        .summary { display: flex; gap: 12px; margin-bottom: 24px; }
        .card { flex: 1; border-radius: 12px; padding: 14px; background: #F1F4F9; }
        .card .label { font-size: 11px; color: #6B7684; text-transform: uppercase; letter-spacing: 0.04em; }
        .card .value { font-size: 18px; font-weight: 700; margin-top: 4px; }
        .income-text { color: #00B37E; }
        .expense-text { color: #FF4D4F; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
        th { text-align: left; font-size: 11px; text-transform: uppercase; color: #6B7684; padding: 6px 8px; border-bottom: 1px solid #E1E6ED; }
        td { padding: 8px; font-size: 13px; border-bottom: 1px solid #F1F4F9; }
        .right { text-align: right; }
        .income { color: #00B37E; }
        .expense { color: #FF4D4F; }
        h2 { font-size: 15px; margin: 18px 0 8px; color: #0B1E3D; }
        .footer { margin-top: 30px; font-size: 11px; color: #9AA5B3; text-align: center; }
      </style>
    </head>
    <body>
      <h1>${title}</h1>
      <div class="subtitle">${subtitle} &middot; Generated by Accounting Partner</div>
      <div class="summary">
        <div class="card">
          <div class="label">Total Income</div>
          <div class="value income-text">${formatCurrency(totalIncome, currency)}</div>
        </div>
        <div class="card">
          <div class="label">Total Expense</div>
          <div class="value expense-text">${formatCurrency(totalExpense, currency)}</div>
        </div>
        <div class="card">
          <div class="label">Profit / Loss</div>
          <div class="value">${formatCurrency(profitLoss, currency)}</div>
        </div>
        <div class="card">
          <div class="label">Transactions</div>
          <div class="value">${transactionCount}</div>
        </div>
      </div>

      <h2>Income by Category</h2>
      <table>
        <thead><tr><th>Category</th><th class="right">Amount</th><th class="right">Share</th></tr></thead>
        <tbody>${breakdownRows(incomeBreakdown, currency) || '<tr><td colspan="3">No income recorded</td></tr>'}</tbody>
      </table>

      <h2>Expense by Category</h2>
      <table>
        <thead><tr><th>Category</th><th class="right">Amount</th><th class="right">Share</th></tr></thead>
        <tbody>${breakdownRows(expenseBreakdown, currency) || '<tr><td colspan="3">No expense recorded</td></tr>'}</tbody>
      </table>

      <h2>Transactions</h2>
      <table>
        <thead><tr><th>Date</th><th>Category</th><th>Type</th><th class="right">Amount</th></tr></thead>
        <tbody>${transactionRows(transactions, currency, dateFormat) || '<tr><td colspan="4">No transactions</td></tr>'}</tbody>
      </table>

      <div class="footer">Accounting Partner &mdash; Developed by MI. AQSHIF AHAMED</div>
    </body>
  </html>`;
}
